/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "introduction",
      className: "custom-sidebar-item",
    },

    {
      type: "html",
      value: '<div class="sidebar-heading">Core Concepts</div>',
    },
    {
      type: "doc",
      id: "core-concepts/architecture-overview",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "core-concepts/workflow",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "core-concepts/components",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "core-concepts/glossary",
      className: "custom-sidebar-item",
    },

    {
      type: "html",
      value: '<div class="sidebar-heading">Validate and Run your Node</div>',
    },
    {
      type: "doc",
      id: "validate-and-run-your-node/overview",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "validate-and-run-your-node/pre-requisites",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "validate-and-run-your-node/run-a-node",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "validate-and-run-your-node/validating-on-testnet",
      className: "custom-sidebar-item",
    },

    {
      type: "html",
      value: '<div class="sidebar-heading">User Guides</div>',
    },
    {
      type: "doc",
      id: "user-guides/quick-start",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "user-guides/tutorials",
      className: "custom-sidebar-item",
    },
    {
      type: "category",
      label: "Deploy Your Rollup",
      className: "custom-sidebar-item",
      items: [
        {
          type: "doc",
          id: "user-guides/deploy-your-rollup/environment-setup",
          className: "custom-sidebar-item",
        },
        {
          type: "doc",
          id: "user-guides/deploy-your-rollup/quick-rollup-deployment",
          className: "custom-sidebar-item",
        },
        {
          type: "doc",
          id: "user-guides/deploy-your-rollup/advanced-rollup-deployment-guide",
          className: "custom-sidebar-item",
        },
      ],
    },

    {
      type: "html",
      value: '<div class="sidebar-heading">Junction Dev Documentation</div>',
    },
    {
      type: "doc",
      id: "junction-dev-docs/api-reference",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "junction-dev-docs/sdk-documentation",
      className: "custom-sidebar-item",
    },
  ],
};

export default sidebars;