/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "introduction",
      className: "custom-sidebar-item",
    },
    {
      type: "html",
      value: '<div class="sidebar-heading">Core Concepts</div>',
    },
    {
      type: "doc",
      id: "framework",
      label: "Architecture Overview",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Workflow",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Components",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Glossary",
      className: "custom-sidebar-item",
    },
    {
      type: "html",
      value: '<div class="sidebar-heading">Validate and Run your Node</div>',
    },
    {
      type: "doc",
      id: "framework",
      label: "Overview",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Pre-requisites",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Running a Node on Testnet",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Validating on Testnet",
      className: "custom-sidebar-item",
    },

    {
      type: "html",
      value: '<div class="sidebar-heading">User Guides</div>',
    },
    {
      type: "doc",
      id: "framework",
      label: "Quick Start",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Tutorials",
      className: "custom-sidebar-item",
    },
    {
      type: "category",
      label: "Deploy Your Rollup",
      className: "custom-sidebar-item",
      link: {
        type: "doc",
        id: "develop/exercise/exercise",
      },
      items: [
        {
          type: "doc",
          id: "framework",
          label: "Environment Setup",
          className: "custom-sidebar-item",
        },
        {
          type: "doc",
          id: "framework",
          label: "Quick Rollup Deployment",
          className: "custom-sidebar-item",
        },
        {
          type: "doc",
          id: "framework",
          label: "Advanced Rollup Deployment Guide",
          className: "custom-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: '<div class="sidebar-heading">JDev Documentation</div>',
    },
    {
      type: "doc",
      id: "framework",
      label: "API Reference",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "SDK Documentation",
      className: "custom-sidebar-item",
    },
    {
      type: "html",
      value: '<div class="sidebar-heading">RDev Documentation</div>',
    },
    {
      type: "doc",
      id: "framework",
      label: "API Reference",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Integration Guides",
      className: "custom-sidebar-item",
    },
    {
      type: "doc",
      id: "framework",
      label: "Environment Setup",
      className: "custom-sidebar-item",
    },
  ],
};

export default sidebars;
