import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-reference/junction-openapi",
    },
    {
      type: "category",
      label: "Query",
      items: [
        {
          type: "doc",
          id: "api-reference/query-check-moniker-availability",
          label: "Queries a list of CheckMonikerAvailability items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-all-batches",
          label: "Queries a list of GetAllBatches items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-batch-info",
          label: "Queries a list of GetBatchInfo items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-rollup-by-moniker",
          label: "Queries a list of GetRollupByMoniker items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-rollup-info",
          label: "Queries a list of GetRollupInfo items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-rollup-staked-amount",
          label: "Queries a list of GetRollupStakedAmount items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-rollups",
          label: "Queries a list of GetRollups items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-stake-details-by-user",
          label: "Queries a list of GetStakeDetailsByUser items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-get-total-staked-amount",
          label: "Queries a list of GetTotalStakedAmount items.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Parameters queries the parameters of the module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-app-options",
          label: "AppOptions returns the autocli options for all of the modules in an app.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/query-account-info",
          label: "AccountInfo queries account info which is common to all account types.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-accounts",
          label: "Accounts returns all the existing accounts.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-account",
          label: "Account returns account details based on address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-account-address-by-id",
          label: "AccountAddressByID returns account address based on account number.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-bech-32-prefix",
          label: "Bech32Prefix queries bech32Prefix",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-address-bytes-to-string",
          label: "AddressBytesToString converts Account Address bytes to string",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-address-string-to-bytes",
          label: "AddressStringToBytes converts Address string to bytes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-module-accounts",
          label: "ModuleAccounts returns all the existing module accounts.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-module-account-by-name",
          label: "ModuleAccountByName returns the module account info by module name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-grants",
          label: "Returns list of `Authorization`, granted to the grantee by the granter.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-grantee-grants",
          label: "GranteeGrants returns a list of `GrantAuthorization` by grantee.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-granter-grants",
          label: "GranterGrants returns list of `GrantAuthorization`, granted by granter.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-all-balances",
          label: "AllBalances queries the balance of all coins for a single account.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-balance",
          label: "Balance queries the balance of a single coin for a single account.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-owners",
          label: "DenomOwners queries for all account addresses that own a particular token\ndenomination.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-owners-by-query",
          label: "DenomOwnersByQuery queries for all account addresses that own a particular token\ndenomination.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denoms-metadata",
          label: "DenomsMetadata queries the client metadata for all registered coin\ndenominations.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-metadata",
          label: "DenomMetadata queries the client metadata of a given coin denomination.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-metadata-by-query-string",
          label: "DenomMetadataByQueryString queries the client metadata of a given coin denomination.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries the parameters of x/bank module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-send-enabled",
          label: "SendEnabled queries for SendEnabled entries.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-spendable-balances",
          label: "SpendableBalances queries the spendable balance of all coins for a single\naccount.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-spendable-balance-by-denom",
          label: "SpendableBalanceByDenom queries the spendable balance of a single denom for\na single account.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-total-supply",
          label: "TotalSupply queries the total supply of all coins.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-supply-of",
          label: "SupplyOf queries the supply of a single coin.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-accounts",
          label: "Account returns account permissions.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-account",
          label: "Account returns account permissions.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-disabled-list",
          label: "DisabledList returns a list of disabled message urls",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries the parameters of x/consensus module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-community-pool",
          label: "CommunityPool queries the community pool coins.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegation-total-rewards",
          label: "DelegationTotalRewards queries the total rewards accrued by each\nvalidator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegation-rewards",
          label: "DelegationRewards queries the total rewards accrued by a delegation.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-validators",
          label: "DelegatorValidators queries the validators of a delegator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-withdraw-address",
          label: "DelegatorWithdrawAddress queries withdraw address of a delegator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries params of the distribution module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-distribution-info",
          label: "ValidatorDistributionInfo queries validator commission and self-delegation rewards for validator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-commission",
          label: "ValidatorCommission queries accumulated commission for a validator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-outstanding-rewards",
          label: "ValidatorOutstandingRewards queries rewards of a validator address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-slashes",
          label: "ValidatorSlashes queries slash events of a validator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-all-evidence",
          label: "AllEvidence queries all evidence.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-evidence",
          label: "Evidence queries evidence based on evidence hash.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-allowance",
          label: "Allowance returns granted allwance to the grantee by the granter.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-allowances",
          label: "Allowances returns all the grants for the given grantee address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-allowances-by-granter",
          label: "AllowancesByGranter returns all the grants given by an address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters of the gov module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposals",
          label: "Proposals queries all proposals based on given status.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposal",
          label: "Proposal queries proposal details based on ProposalID.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-deposits",
          label: "Deposits queries all deposits of a single proposal.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-deposit",
          label: "Deposit queries single deposit information based on proposalID, depositor address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-tally-result",
          label: "TallyResult queries the tally of a proposal vote.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-votes",
          label: "Votes queries votes of a given proposal.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-vote",
          label: "Vote queries voted information based on proposalID, voterAddr.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-constitution",
          label: "Constitution queries the chain's constitution.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters of the gov module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposals",
          label: "Proposals queries all proposals based on given status.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposal",
          label: "Proposal queries proposal details based on ProposalID.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-deposits",
          label: "Deposits queries all deposits of a single proposal.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-deposit",
          label: "Deposit queries single deposit information based on proposalID, depositAddr.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-tally-result",
          label: "TallyResult queries the tally of a proposal vote.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-votes",
          label: "Votes queries votes of a given proposal.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-vote",
          label: "Vote queries voted information based on proposalID, voterAddr.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-group-info",
          label: "GroupInfo queries group info based on group id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-group-members",
          label: "GroupMembers queries members of a group by group id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-group-policies-by-admin",
          label: "GroupPoliciesByAdmin queries group policies by admin address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-group-policies-by-group",
          label: "GroupPoliciesByGroup queries group policies by group id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-group-policy-info",
          label: "GroupPolicyInfo queries group policy info based on account address of group policy.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-groups",
          label: "Groups queries all groups in state.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-groups-by-admin",
          label: "GroupsByAdmin queries groups by admin address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-groups-by-member",
          label: "GroupsByMember queries groups by member address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposal",
          label: "Proposal queries a proposal based on proposal id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-tally-result",
          label: "TallyResult returns the tally result of a proposal. If the proposal is\nstill in voting period, then this query computes the current tally state,\nwhich might not be final. On the other hand, if the proposal is final,\nthen it simply returns the `final_tally_result` state stored in the\nproposal itself.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-proposals-by-group-policy",
          label: "ProposalsByGroupPolicy queries proposals based on account address of group policy.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-vote-by-proposal-voter",
          label: "VoteByProposalVoter queries a vote by proposal id and voter.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-votes-by-proposal",
          label: "VotesByProposal queries a vote by proposal id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-votes-by-voter",
          label: "VotesByVoter queries a vote by voter.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-annual-provisions",
          label: "AnnualProvisions current minting annual provisions value.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-inflation",
          label: "Inflation returns the current minting inflation value.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params returns the total set of minting parameters.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-balance",
          label: "Balance queries the number of NFTs of a given class owned by the owner, same as balanceOf in ERC721",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-classes",
          label: "Classes queries all NFT classes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-class",
          label: "Class queries an NFT class based on its id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-nf-ts",
          label: "NFTs queries all NFTs of a given class or owner,choose at least one of the two, similar to tokenByIndex in\nERC721Enumerable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-nft",
          label: "NFT queries an NFT based on its class and id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-owner",
          label: "Owner queries the owner of the NFT based on its class and id, same as ownerOf in ERC721",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-supply",
          label: "Supply queries the number of NFTs from the given class, same as totalSupply of ERC721.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries a specific parameter of a module, given its subspace and\nkey.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-subspaces",
          label: "Subspaces queries for all registered subspaces and all keys for a subspace.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries the parameters of slashing module",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-signing-infos",
          label: "SigningInfos queries signing info of all validators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-signing-info",
          label: "SigningInfo queries the signing info of given cons address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-delegations",
          label: "DelegatorDelegations queries all delegations of a given delegator address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-redelegations",
          label: "Redelegations queries redelegations of given address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-unbonding-delegations",
          label: "DelegatorUnbondingDelegations queries all unbonding delegations of a given\ndelegator address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-validators",
          label: "DelegatorValidators queries all validators info for given delegator\naddress.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegator-validator",
          label: "DelegatorValidator queries validator info for given delegator validator\npair.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-historical-info",
          label: "HistoricalInfo queries the historical info for given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Parameters queries the staking parameters.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-pool",
          label: "Pool queries the pool info.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validators",
          label: "Validators queries all validators that match the given status.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator",
          label: "Validator queries validator info for given validator address.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-delegations",
          label: "ValidatorDelegations queries delegate info for given validator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-delegation",
          label: "Delegation queries delegate info for given validator delegator pair.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-unbonding-delegation",
          label: "UnbondingDelegation queries unbonding info for given validator delegator\npair.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-validator-unbonding-delegations",
          label: "ValidatorUnbondingDelegations queries unbonding delegations of a validator.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-applied-plan",
          label: "AppliedPlan queries a previously applied upgrade plan by its name.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-authority",
          label: "Returns the account with authority to conduct upgrades",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-current-plan",
          label: "CurrentPlan queries the current upgrade plan.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-module-versions",
          label: "ModuleVersions queries the list of module versions from state.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-upgraded-consensus-state",
          label: "UpgradedConsensusState queries the consensus state that will serve\nas a trusted kernel for the next version of this chain. It will only be\nstored at the last height of this chain.\nUpgradedConsensusState RPC not supported with legacy querier\nThis rpc is deprecated now that IBC has its own replacement\n(https://github.com/cosmos/ibc-go/blob/2c880a22e9f9cc75f62b527ca94aa75ce1106001/proto/ibc/core/client/v1/query.proto#L54)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-fee-enabled-channel",
          label: "FeeEnabledChannel returns true if the provided port and channel identifiers belong to a fee enabled channel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-incentivized-packets-for-channel",
          label: "Gets all incentivized packets for a specific channel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-counterparty-payee",
          label: "CounterpartyPayee returns the registered counterparty payee for forward relaying",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-payee",
          label: "Payee returns the registered payee address for a specific channel given the relayer address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-incentivized-packet",
          label: "IncentivizedPacket returns all packet fees for a packet given its identifier",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-total-ack-fees",
          label: "TotalAckFees returns the total acknowledgement fees for a packet given its identifier",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-total-recv-fees",
          label: "TotalRecvFees returns the total receive fees for a packet given its identifier",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-total-timeout-fees",
          label: "TotalTimeoutFees returns the total timeout fees for a packet given its identifier",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-fee-enabled-channels",
          label: "FeeEnabledChannels returns a list of all fee enabled channels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-incentivized-packets",
          label: "IncentivizedPackets returns all incentivized packets and their associated fees",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-interchain-account",
          label: "InterchainAccount returns the interchain account address for a given owner address on a given connection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters of the ICA controller submodule.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters of the ICA host submodule.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-escrow-address",
          label: "EscrowAddress returns the escrow address for a particular port and channel id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-hash",
          label: "DenomHash queries a denomination hash information.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-traces",
          label: "DenomTraces queries all denomination traces.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-denom-trace",
          label: "DenomTrace queries a denomination trace information.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-total-escrow-for-denom",
          label: "TotalEscrowForDenom returns the total amount of tokens in escrow based on the denom.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params queries all parameters of the ibc-transfer module.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-channels",
          label: "Channels queries all the IBC channels of a chain.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-channel",
          label: "Channel queries an IBC Channel.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-channel-client-state",
          label: "ChannelClientState queries for the client state for the channel associated\nwith the provided channel identifiers.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-channel-consensus-state",
          label: "ChannelConsensusState queries for the consensus state for the channel\nassociated with the provided channel identifiers.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-next-sequence-receive",
          label: "NextSequenceReceive returns the next receive sequence for a given channel.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-next-sequence-send",
          label: "NextSequenceSend returns the next send sequence for a given channel.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-packet-acknowledgements",
          label: "PacketAcknowledgements returns all the packet acknowledgements associated\nwith a channel.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-packet-acknowledgement",
          label: "PacketAcknowledgement queries a stored packet acknowledgement hash.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-packet-commitments",
          label: "PacketCommitments returns all the packet commitments hashes associated\nwith a channel.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-unreceived-acks",
          label: "UnreceivedAcks returns all the unreceived IBC acknowledgements associated\nwith a channel and sequences.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-unreceived-packets",
          label: "UnreceivedPackets returns all the unreceived IBC packets associated with a\nchannel and sequences.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-packet-commitment",
          label: "PacketCommitment queries a stored packet commitment hash.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-packet-receipt",
          label: "PacketReceipt queries if a given packet sequence has been received on the\nqueried chain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-upgrade",
          label: "Upgrade returns the upgrade for a given port and channel id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-upgrade-error",
          label: "UpgradeError returns the error receipt if the upgrade handshake failed.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connection-channels",
          label: "ConnectionChannels queries all the channels associated with a connection\nend.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-channel-params",
          label: "ChannelParams queries all parameters of the ibc channel submodule.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-client-states",
          label: "ClientStates queries all the IBC light clients of a chain.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-client-state",
          label: "ClientState queries an IBC light client.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-client-status",
          label: "Status queries the status of an IBC client.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-consensus-states",
          label: "ConsensusStates queries all the consensus state associated with a given\nclient.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-consensus-state-heights",
          label: "ConsensusStateHeights queries the height of every consensus states associated with a given client.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-consensus-state",
          label: "ConsensusState queries a consensus state associated with a client state at\na given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-client-params",
          label: "ClientParams queries all parameters of the ibc client submodule.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-upgraded-client-state",
          label: "UpgradedClientState queries an Upgraded IBC light client.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-upgraded-consensus-state",
          label: "UpgradedConsensusState queries an Upgraded IBC consensus state.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-verify-membership",
          label: "VerifyMembership queries an IBC light client for proof verification of a value at a given key path.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/query-client-connections",
          label: "ClientConnections queries the connection paths associated with a client\nstate.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connections",
          label: "Connections queries all the IBC connections of a chain.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connection",
          label: "Connection queries an IBC connection end.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connection-client-state",
          label: "ConnectionClientState queries the client state associated with the\nconnection.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connection-consensus-state",
          label: "ConnectionConsensusState queries the consensus state associated with the\nconnection.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-connection-params",
          label: "ConnectionParams queries all parameters of the ibc connection submodule.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-checksums",
          label: "Get all Wasm checksums",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-code",
          label: "Get Wasm code for given checksum",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-codes",
          label: "Codes gets the metadata for all stored wasm codes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-code",
          label: "Code gets the binary code and metadata for a singe wasm code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-contracts-by-code",
          label: "ContractsByCode lists all smart contracts for a code id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-params",
          label: "Params gets the module params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-pinned-codes",
          label: "PinnedCodes gets the pinned code ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-contract-info",
          label: "ContractInfo gets the contract meta data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-contract-history",
          label: "ContractHistory gets the contract code history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-raw-contract-state",
          label: "RawContractState gets single key from the raw store data of a contract",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-smart-contract-state",
          label: "SmartContractState get smart query result from the contract",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-all-contract-state",
          label: "AllContractState gets all raw store data for a single contract",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-build-address",
          label: "BuildAddress builds a contract address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/query-contracts-by-creator",
          label: "ContractsByCreator gets the contracts by creator",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Msg",
      items: [
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a (governance) operation for updating the x/auth module\nparameters. The authority defaults to the x/gov module account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-exec",
          label: "Exec attempts to execute the provided messages using\nauthorizations granted to the grantee. Each message should have only\none signer corresponding to the granter of the authorization.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-grant",
          label: "Grant grants the provided authorization to the grantee on the granter's\naccount with the provided expiration time. If there is already a grant\nfor the given (granter, grantee, Authorization) triple, then the grant\nwill be overwritten.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-revoke",
          label: "Revoke revokes any authorization corresponding to the provided method name on the\ngranter's account that has been granted to the grantee.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-multi-send",
          label: "MultiSend defines a method for sending coins from some accounts to other accounts.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-send",
          label: "Send defines a method for sending coins from one account to another account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-set-send-enabled",
          label: "SetSendEnabled is a governance operation for setting the SendEnabled flag\non any number of Denoms. Only the entries to add or update should be\nincluded. Entries that already exist in the store, but that aren't\nincluded in this message, will be left unchanged.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/bank module parameters.\nThe authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-authorize-circuit-breaker",
          label: "AuthorizeCircuitBreaker allows a super-admin to grant (or revoke) another\naccount's circuit breaker permissions.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-reset-circuit-breaker",
          label: "ResetCircuitBreaker resumes processing of Msg's in the state machine that\nhave been been paused using TripCircuitBreaker.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-trip-circuit-breaker",
          label: "TripCircuitBreaker pauses processing of Msg's in the state machine.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/consensus module parameters.\nThe authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/crisis module\nparameters. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-verify-invariant",
          label: "VerifyInvariant defines a method to verify a particular invariant.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-community-pool-spend",
          label: "CommunityPoolSpend defines a governance operation for sending tokens from\nthe community pool in the x/distribution module to another account, which\ncould be the governance module itself. The authority is defined in the\nkeeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-deposit-validator-rewards-pool",
          label: "DepositValidatorRewardsPool defines a method to provide additional rewards\nto delegators to a specific validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-fund-community-pool",
          label: "FundCommunityPool defines a method to allow an account to directly\nfund the community pool.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-set-withdraw-address",
          label: "SetWithdrawAddress defines a method to change the withdraw address\nfor a delegator (or validator self-delegation).",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/distribution\nmodule parameters. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-withdraw-delegator-reward",
          label: "WithdrawDelegatorReward defines a method to withdraw rewards of delegator\nfrom a single validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-withdraw-validator-commission",
          label: "WithdrawValidatorCommission defines a method to withdraw the\nfull commission to the validator address.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-evidence",
          label: "SubmitEvidence submits an arbitrary Evidence of misbehavior such as equivocation or\ncounterfactual signing.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-grant-allowance",
          label: "GrantAllowance grants fee allowance to the grantee on the granter's\naccount with the provided expiration time.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-prune-allowances",
          label: "PruneAllowances prunes expired fee allowances, currently up to 75 at a time.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-revoke-allowance",
          label: "RevokeAllowance revokes any fee allowance of granter's account that\nhas been granted to the grantee.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-deposit",
          label: "Deposit defines a method to add deposit on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-proposal",
          label: "SubmitProposal defines a method to create new proposal given a content.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-vote",
          label: "Vote defines a method to add a vote on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-vote-weighted",
          label: "VoteWeighted defines a method to add a weighted vote on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-cancel-proposal",
          label: "CancelProposal defines a method to cancel governance proposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-deposit",
          label: "Deposit defines a method to add deposit on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-exec-legacy-content",
          label: "ExecLegacyContent defines a Msg to be in included in a MsgSubmitProposal\nto execute a legacy content-based proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-proposal",
          label: "SubmitProposal defines a method to create new proposal given the messages.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/gov module\nparameters. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-vote",
          label: "Vote defines a method to add a vote on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-vote-weighted",
          label: "VoteWeighted defines a method to add a weighted vote on a specific proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-group",
          label: "CreateGroup creates a new group with an admin account address, a list of members and some optional metadata.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-group-policy",
          label: "CreateGroupPolicy creates a new group policy using given DecisionPolicy.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-group-with-policy",
          label: "CreateGroupWithPolicy creates a new group with policy.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-exec",
          label: "Exec executes a proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-leave-group",
          label: "LeaveGroup allows a group member to leave the group.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-proposal",
          label: "SubmitProposal submits a new proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-admin",
          label: "UpdateGroupAdmin updates the group admin with given group id and previous admin address.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-members",
          label: "UpdateGroupMembers updates the group members with given group id and admin address.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-metadata",
          label: "UpdateGroupMetadata updates the group metadata with given group id and admin address.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-policy-admin",
          label: "UpdateGroupPolicyAdmin updates a group policy admin.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-policy-decision-policy",
          label: "UpdateGroupPolicyDecisionPolicy allows a group policy's decision policy to be updated.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-group-policy-metadata",
          label: "UpdateGroupPolicyMetadata updates a group policy metadata.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-vote",
          label: "Vote allows a voter to vote on a proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-withdraw-proposal",
          label: "WithdrawProposal withdraws a proposal.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/mint module\nparameters. The authority is defaults to the x/gov module account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-send",
          label: "Send defines a method to send a nft from one account to another account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-unjail",
          label: "Unjail defines a method for unjailing a jailed validator, thus returning\nthem into the bonded validator set, so they can begin receiving provisions\nand rewards again.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/slashing module\nparameters. The authority defaults to the x/gov module account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-begin-redelegate",
          label: "BeginRedelegate defines a method for performing a redelegation\nof coins from a delegator and source validator to a destination validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-cancel-unbonding-delegation",
          label: "CancelUnbondingDelegation defines a method for performing canceling the unbonding delegation\nand delegate back to previous validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-validator",
          label: "CreateValidator defines a method for creating a new validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-delegate",
          label: "Delegate defines a method for performing a delegation of coins\nfrom a delegator to a validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-edit-validator",
          label: "EditValidator defines a method for editing an existing validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-undelegate",
          label: "Undelegate defines a method for performing an undelegation from a\ndelegate and a validator.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines an operation for updating the x/staking module\nparameters.\nSince: cosmos-sdk 0.47",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-cancel-upgrade",
          label: "CancelUpgrade is a governance operation for cancelling a previously\napproved software upgrade.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-software-upgrade",
          label: "SoftwareUpgrade is a governance operation for initiating a software upgrade.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-periodic-vesting-account",
          label: "CreatePeriodicVestingAccount defines a method that enables creating a\nperiodic vesting account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-permanent-locked-account",
          label: "CreatePermanentLockedAccount defines a method that enables creating a permanent\nlocked account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-vesting-account",
          label: "CreateVestingAccount defines a method that enables creating a vesting\naccount.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-pay-packet-fee",
          label: "PayPacketFee defines a rpc handler method for MsgPayPacketFee\nPayPacketFee is an open callback that may be called by any module/user that wishes to escrow funds in order to\nincentivize the relaying of the packet at the next sequence\nNOTE: This method is intended to be used within a multi msg transaction, where the subsequent msg that follows\ninitiates the lifecycle of the incentivized packet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-pay-packet-fee-async",
          label: "PayPacketFeeAsync defines a rpc handler method for MsgPayPacketFeeAsync\nPayPacketFeeAsync is an open callback that may be called by any module/user that wishes to escrow funds in order to\nincentivize the relaying of a known packet (i.e. at a particular sequence)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-register-counterparty-payee",
          label: "RegisterCounterpartyPayee defines a rpc handler method for MsgRegisterCounterpartyPayee\nRegisterCounterpartyPayee is called by the relayer on each channelEnd and allows them to specify the counterparty\npayee address before relaying. This ensures they will be properly compensated for forward relaying since\nthe destination chain must include the registered counterparty payee address in the acknowledgement. This function\nmay be called more than once by a relayer, in which case, the latest counterparty payee address is always used.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-register-payee",
          label: "RegisterPayee defines a rpc handler method for MsgRegisterPayee\nRegisterPayee is called by the relayer on each channelEnd and allows them to set an optional\npayee to which reverse and timeout relayer packet fees will be paid out. The payee should be registered on\nthe source chain from which packets originate as this is where fee distribution takes place. This function may be\ncalled more than once by a relayer, in which case, the latest payee is always used.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-register-interchain-account",
          label: "RegisterInterchainAccount defines a rpc handler for MsgRegisterInterchainAccount.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-send-tx",
          label: "SendTx defines a rpc handler for MsgSendTx.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a rpc handler for MsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-module-query-safe",
          label: "ModuleQuerySafe defines a rpc handler for MsgModuleQuerySafe.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a rpc handler for MsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-transfer",
          label: "Transfer defines a rpc handler method for MsgTransfer.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a rpc handler for MsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-acknowledgement",
          label: "Acknowledgement defines a rpc handler method for MsgAcknowledgement.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-close-confirm",
          label: "ChannelCloseConfirm defines a rpc handler method for\nMsgChannelCloseConfirm.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-close-init",
          label: "ChannelCloseInit defines a rpc handler method for MsgChannelCloseInit.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-open-ack",
          label: "ChannelOpenAck defines a rpc handler method for MsgChannelOpenAck.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-open-confirm",
          label: "ChannelOpenConfirm defines a rpc handler method for MsgChannelOpenConfirm.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-open-init",
          label: "ChannelOpenInit defines a rpc handler method for MsgChannelOpenInit.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-open-try",
          label: "ChannelOpenTry defines a rpc handler method for MsgChannelOpenTry.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-ack",
          label: "ChannelUpgradeAck defines a rpc handler method for MsgChannelUpgradeAck.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-cancel",
          label: "ChannelUpgradeCancel defines a rpc handler method for MsgChannelUpgradeCancel.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-confirm",
          label: "ChannelUpgradeConfirm defines a rpc handler method for MsgChannelUpgradeConfirm.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-init",
          label: "ChannelUpgradeInit defines a rpc handler method for MsgChannelUpgradeInit.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-open",
          label: "ChannelUpgradeOpen defines a rpc handler method for MsgChannelUpgradeOpen.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-timeout",
          label: "ChannelUpgradeTimeout defines a rpc handler method for MsgChannelUpgradeTimeout.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-channel-upgrade-try",
          label: "ChannelUpgradeTry defines a rpc handler method for MsgChannelUpgradeTry.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-prune-acknowledgements",
          label: "PruneAcknowledgements defines a rpc handler method for MsgPruneAcknowledgements.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-recv-packet",
          label: "RecvPacket defines a rpc handler method for MsgRecvPacket.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-timeout",
          label: "Timeout defines a rpc handler method for MsgTimeout.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-timeout-on-close",
          label: "TimeoutOnClose defines a rpc handler method for MsgTimeoutOnClose.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-channel-params",
          label: "UpdateChannelParams defines a rpc handler method for MsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-create-client",
          label: "CreateClient defines a rpc handler method for MsgCreateClient.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-ibc-software-upgrade",
          label: "IBCSoftwareUpgrade defines a rpc handler method for MsgIBCSoftwareUpgrade.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-recover-client",
          label: "RecoverClient defines a rpc handler method for MsgRecoverClient.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-misbehaviour",
          label: "SubmitMisbehaviour defines a rpc handler method for MsgSubmitMisbehaviour.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-client",
          label: "UpdateClient defines a rpc handler method for MsgUpdateClient.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-client-params",
          label: "UpdateClientParams defines a rpc handler method for MsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-upgrade-client",
          label: "UpgradeClient defines a rpc handler method for MsgUpgradeClient.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-connection-open-ack",
          label: "ConnectionOpenAck defines a rpc handler method for MsgConnectionOpenAck.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-connection-open-confirm",
          label: "ConnectionOpenConfirm defines a rpc handler method for\nMsgConnectionOpenConfirm.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-connection-open-init",
          label: "ConnectionOpenInit defines a rpc handler method for MsgConnectionOpenInit.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-connection-open-try",
          label: "ConnectionOpenTry defines a rpc handler method for MsgConnectionOpenTry.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-connection-params",
          label: "UpdateConnectionParams defines a rpc handler method for\nMsgUpdateParams.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-migrate-contract",
          label: "MigrateContract defines a rpc handler method for MsgMigrateContract.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-remove-checksum",
          label: "RemoveChecksum defines a rpc handler method for MsgRemoveChecksum.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-store-code",
          label: "StoreCode defines a rpc handler method for MsgStoreCode.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-init-prover",
          label: "Msg_InitProver",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-init-rollup",
          label: "Msg_InitRollup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-batch",
          label: "Msg_SubmitBatch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-submit-batch-metadata",
          label: "Msg_SubmitBatchMetadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a (governance) operation for updating the module\nparameters. The authority defaults to the x/gov module account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-add-code-upload-params-addresses",
          label: "AddCodeUploadParamsAddresses defines a governance operation for\nadding addresses to code upload params.\nThe authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-clear-admin",
          label: "ClearAdmin removes any admin stored for a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-execute-contract",
          label: "Execute submits the given message data to a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-instantiate-contract",
          label: "InstantiateContract creates a new smart contract instance for the given\n code id.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-instantiate-contract-2",
          label: "InstantiateContract2 creates a new smart contract instance for the given\n code id with a predictable address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-migrate-contract",
          label: "Migrate runs a code upgrade/ downgrade for a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-pin-codes",
          label: "PinCodes defines a governance operation for pinning a set of\ncode ids in the wasmvm cache. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-remove-code-upload-params-addresses",
          label: "RemoveCodeUploadParamsAddresses defines a governance operation for\nremoving addresses from code upload params.\nThe authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-store-and-instantiate-contract",
          label: "StoreAndInstantiateContract defines a governance operation for storing\nand instantiating the contract. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-store-and-migrate-contract",
          label: "StoreAndMigrateContract defines a governance operation for storing\nand migrating the contract. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-store-code",
          label: "StoreCode to submit Wasm code to the system",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-sudo-contract",
          label: "SudoContract defines a governance operation for calling sudo\non a contract. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-unpin-codes",
          label: "UnpinCodes defines a governance operation for unpinning a set of\ncode ids in the wasmvm cache. The authority is defined in the keeper.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-admin",
          label: "UpdateAdmin sets a new admin for a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-contract-label",
          label: "UpdateContractLabel sets a new label for a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-instantiate-config",
          label: "UpdateInstantiateConfig updates instantiate config for a smart contract",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/msg-update-params",
          label: "UpdateParams defines a governance operation for updating the x/wasm\nmodule parameters. The authority is defined in the keeper.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ABCIListenerService",
      items: [
        {
          type: "doc",
          id: "api-reference/abci-listener-service-listen-commit",
          label: "ListenCommit is the corresponding endpoint for ABCIListener.ListenCommit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-listener-service-listen-finalize-block",
          label: "ListenFinalizeBlock is the corresponding endpoint for ABCIListener.ListenEndBlock",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Service",
      items: [
        {
          type: "doc",
          id: "api-reference/service-config",
          label: "Config queries for the operator configuration.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-status",
          label: "Status queries for the node status.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-abci-query",
          label: "ABCIQuery defines a query handler that supports ABCI queries directly to the\napplication, bypassing Tendermint completely. The ABCI query must contain\na valid and supported path, including app, custom, p2p, and store.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-block-by-height",
          label: "GetBlockByHeight queries block for given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-latest-block",
          label: "GetLatestBlock returns the latest block.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-node-info",
          label: "GetNodeInfo queries the current node info.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-syncing",
          label: "GetSyncing queries node syncing.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-validator-set-by-height",
          label: "GetValidatorSetByHeight queries validator-set at a given height.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-latest-validator-set",
          label: "GetLatestValidatorSet queries latest validator-set.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-tx-decode",
          label: "TxDecode decodes the transaction.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/service-tx-decode-amino",
          label: "TxDecodeAmino decodes an Amino transaction from encoded bytes to JSON.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/service-tx-encode",
          label: "TxEncode encodes the transaction.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/service-tx-encode-amino",
          label: "TxEncodeAmino encodes an Amino transaction from JSON to encoded bytes.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/service-simulate",
          label: "Simulate simulates executing a transaction for estimating gas usage.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/service-get-tx",
          label: "GetTx fetches a tx by hash.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/service-get-block-with-txs",
          label: "GetBlockWithTxs fetches a block with decoded txs.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ReflectionService",
      items: [
        {
          type: "doc",
          id: "api-reference/reflection-service-get-authn-descriptor",
          label: "GetAuthnDescriptor returns information on how to authenticate transactions in the application\nNOTE: this RPC is still experimental and might be subject to breaking changes or removal in\nfuture releases of the cosmos-sdk.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-get-chain-descriptor",
          label: "GetChainDescriptor returns the description of the chain",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-get-codec-descriptor",
          label: "GetCodecDescriptor returns the descriptor of the codec of the application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-get-configuration-descriptor",
          label: "GetConfigurationDescriptor returns the descriptor for the sdk.Config of the application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-get-query-services-descriptor",
          label: "GetQueryServicesDescriptor returns the available gRPC queryable services of the application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-get-tx-descriptor",
          label: "GetTxDescriptor returns information on the used transaction object and available msgs that can be used",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-list-all-interfaces",
          label: "ListAllInterfaces lists all the interfaces registered in the interface\nregistry.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/reflection-service-list-implementations",
          label: "ListImplementations list all the concrete types that implement a given\ninterface.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ABCI",
      items: [
        {
          type: "doc",
          id: "api-reference/abci-apply-snapshot-chunk",
          label: "ABCI_ApplySnapshotChunk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-check-tx",
          label: "ABCI_CheckTx",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-commit",
          label: "ABCI_Commit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-echo",
          label: "ABCI_Echo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-extend-vote",
          label: "ABCI_ExtendVote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-finalize-block",
          label: "ABCI_FinalizeBlock",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-flush",
          label: "ABCI_Flush",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-info",
          label: "ABCI_Info",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-init-chain",
          label: "ABCI_InitChain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-list-snapshots",
          label: "ABCI_ListSnapshots",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-load-snapshot-chunk",
          label: "ABCI_LoadSnapshotChunk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-offer-snapshot",
          label: "ABCI_OfferSnapshot",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-prepare-proposal",
          label: "ABCI_PrepareProposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-process-proposal",
          label: "ABCI_ProcessProposal",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-query",
          label: "ABCI_Query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/abci-verify-vote-extension",
          label: "ABCI_VerifyVoteExtension",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
