name: Auto Deploy Airchains Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 148.113.38.220
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            echo "🚀 Starting remote deployment..."
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh
            echo "✅ Deployment complete!"
